//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CShroudApp.Desktop.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CShroudApp.Desktop.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Day!.
        /// </summary>
        public static string GreetingText {
            get {
                return ResourceManager.GetString("GreetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Mode.
        /// </summary>
        public static string TrayUiChangeMode {
            get {
                return ResourceManager.GetString("TrayUiChangeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayUiExit {
            get {
                return ResourceManager.GetString("TrayUiExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide CrimsonShroud.
        /// </summary>
        public static string TrayUiHideApp {
            get {
                return ResourceManager.GetString("TrayUiHideApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show CrimsonShroud.
        /// </summary>
        public static string TrayUiShowApp {
            get {
                return ResourceManager.GetString("TrayUiShowApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        public static string VpnModeProxy {
            get {
                return ResourceManager.GetString("VpnModeProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        public static string VpnModeTransparentProxy {
            get {
                return ResourceManager.GetString("VpnModeTransparentProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN.
        /// </summary>
        public static string VpnModeTun {
            get {
                return ResourceManager.GetString("VpnModeTun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN&amp;Proxy.
        /// </summary>
        public static string VpnModeTunPlusProxy {
            get {
                return ResourceManager.GetString("VpnModeTunPlusProxy", resourceCulture);
            }
        }
    }
}
