//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CShroudApp.Desktop.Assets.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CShroudApp.Desktop.Assets.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Day!.
        /// </summary>
        public static string GreetingText {
            get {
                return ResourceManager.GetString("GreetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Mode.
        /// </summary>
        public static string TrayUiChangeMode {
            get {
                return ResourceManager.GetString("TrayUiChangeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayUiExit {
            get {
                return ResourceManager.GetString("TrayUiExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide CrimsonShroud.
        /// </summary>
        public static string TrayUiHideApp {
            get {
                return ResourceManager.GetString("TrayUiHideApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show CrimsonShroud.
        /// </summary>
        public static string TrayUiShowApp {
            get {
                return ResourceManager.GetString("TrayUiShowApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UiAuthCancelButton {
            get {
                return ResourceManager.GetString("UiAuthCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔒 Enterprise-grade encryption • 🌍 Global server network • ⚡ Zero-log policy.
        /// </summary>
        public static string UiAuthCrimsonShroudFooter {
            get {
                return ResourceManager.GetString("UiAuthCrimsonShroudFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect securely and protect your digital freedom.
        /// </summary>
        public static string UiAuthCrimsonShroudText {
            get {
                return ResourceManager.GetString("UiAuthCrimsonShroudText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue with Telegram.
        /// </summary>
        public static string UiAuthLoginViaTelegramButton {
            get {
                return ResourceManager.GetString("UiAuthLoginViaTelegramButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to server....
        /// </summary>
        public static string UiAuthLoginViaTelegramButtonConnecting {
            get {
                return ResourceManager.GetString("UiAuthLoginViaTelegramButtonConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Telegram.
        /// </summary>
        public static string UiAuthOpenTelegramButton {
            get {
                return ResourceManager.GetString("UiAuthOpenTelegramButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string UiAuthOR {
            get {
                return ResourceManager.GetString("UiAuthOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string UiAuthRetryLoginViaTelegramButton {
            get {
                return ResourceManager.GetString("UiAuthRetryLoginViaTelegramButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry via {0}s.
        /// </summary>
        public static string UiAuthRetryLoginViaTelegramButtonCountingDown {
            get {
                return ResourceManager.GetString("UiAuthRetryLoginViaTelegramButtonCountingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string UiAuthSignIn {
            get {
                return ResourceManager.GetString("UiAuthSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Failed.
        /// </summary>
        public static string UiAuthVerificationFailed {
            get {
                return ResourceManager.GetString("UiAuthVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that the wrong option was selected or the session has expired..
        /// </summary>
        public static string UiAuthVerificationFailedText {
            get {
                return ResourceManager.GetString("UiAuthVerificationFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You could try it again or later.
        /// </summary>
        public static string UiAuthVerificationFailedText2 {
            get {
                return ResourceManager.GetString("UiAuthVerificationFailedText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Required.
        /// </summary>
        public static string UiAuthVerificationRequired {
            get {
                return ResourceManager.GetString("UiAuthVerificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click the button with this code in your Telegram app:.
        /// </summary>
        public static string UiAuthVerificationRequiredText {
            get {
                return ResourceManager.GetString("UiAuthVerificationRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Success.
        /// </summary>
        public static string UiAuthVerificationSuccess {
            get {
                return ResourceManager.GetString("UiAuthVerificationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are already authorizing you in the system..
        /// </summary>
        public static string UiAuthVerificationSuccessText {
            get {
                return ResourceManager.GetString("UiAuthVerificationSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait a moment ❤️ㅤ.
        /// </summary>
        public static string UiAuthVerificationSuccessText2 {
            get {
                return ResourceManager.GetString("UiAuthVerificationSuccessText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        public static string VpnModeProxy {
            get {
                return ResourceManager.GetString("VpnModeProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        public static string VpnModeTransparentProxy {
            get {
                return ResourceManager.GetString("VpnModeTransparentProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN.
        /// </summary>
        public static string VpnModeTun {
            get {
                return ResourceManager.GetString("VpnModeTun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN&amp;Proxy.
        /// </summary>
        public static string VpnModeTunPlusProxy {
            get {
                return ResourceManager.GetString("VpnModeTunPlusProxy", resourceCulture);
            }
        }
    }
}
