<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <RootNamespace>CShroudApp.Desktop</RootNamespace>

        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Backend\Backend.csproj"/>
    </ItemGroup>
    
    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <ProjectCapability Include="Avalonia" />
        <TrimmerRootAssembly Include="Avalonia.Themes.Fluent" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.Desktop"/>
        <PackageReference Include="Avalonia.Labs.Gif" />
        <PackageReference Include="Avalonia.Labs.Lottie" />
        <PackageReference Include="Avalonia.Themes.Fluent"/>
        <PackageReference Include="Avalonia.Fonts.Inter"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics"/>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Assets\Localization\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <PublicClass>true</PublicClass>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
            <StronglyTypedFileName>Assets\Resources.Designer.cs</StronglyTypedFileName>
            <StronglyTypedLanguage>CSharp</StronglyTypedLanguage>
            <StronglyTypedNamespace>CShroudApp.Desktop.Assets.Localization</StronglyTypedNamespace>
            <StronglyTypedClassName>Resources</StronglyTypedClassName>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Assets\icons\ico\" />
      <Folder Include="Resources\Panels\" />
      <Folder Include="Resources\Templates\" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Resources\Panels\Auth\DefaultLoginPanel.axaml" />
    </ItemGroup>

    <ItemGroup>
      <AvaloniaXaml Update="Widgets\IconButtonGeneric.axaml">
        <DependentUpon>IconButton.cs</DependentUpon>
      </AvaloniaXaml>
    </ItemGroup>

    <!--<ItemGroup>
        <Compile Update="Assets\Localization\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
    </ItemGroup>-->
</Project>
